FROM ubuntu:16.04

RUN adduser flask --disabled-password --disabled-login
RUN apt-get update && apt-get -y install python3 python3-pip python3-venv git virtualenv wget curl

COPY . /app
# Clean previous virtualenv
WORKDIR /app
RUN if [ -e venv ]; then rm -rf venv; fi

RUN chown -R flask:flask /app

USER flask
EXPOSE 5000

RUN ["make", "environment"]
