"""empty message

Revision ID: 81669735c6e7
Revises: 
Create Date: 2019-03-05 13:09:42.310791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81669735c6e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_group_chat', sa.Integer(), nullable=True),
    sa.Column('topic', sa.String(length=1000), nullable=False),
    sa.Column('added_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat')
    # ### end Alembic commands ###
