"""empty message

Revision ID: e31bd64661cc
Revises: d94ae0844155
Create Date: 2019-03-27 02:38:11.506705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e31bd64661cc'
down_revision = 'd94ae0844155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('members_user_id_fkey', 'members', type_='foreignkey')
    op.drop_constraint('members_chat_id_fkey', 'members', type_='foreignkey')
    op.create_foreign_key(None, 'members', 'chats', ['chat_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'members', 'users', ['user_id'], ['id'], ondelete='cascade')
    op.add_column('users', sa.Column('email', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.create_foreign_key('members_chat_id_fkey', 'members', 'chats', ['chat_id'], ['id'])
    op.create_foreign_key('members_user_id_fkey', 'members', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
